jmxtrans/jmxtrans

pom.xml, src/com/googlecode/jmxtrans/cli/CliArgumentParser.java, src/com/googlecode/jmxtrans/jmx/JmxResultProcessor.java, test/com/googlecode/jmxtrans/jmx/JmxResultProcessorTest.java
I have a jmx enabled application that returns a Map object as the attribute value and the final commit here simply passes the Map object to the getNewResultObject method
The other two commits reflect changes I needed in order to run the jar:
compiled on Windows 7 Java jdk1.7.0_09 mvn  3.0.5 
and run on CentOS release 6.6 (Final) java-1.7.0-openjdk-devel-1.7.0.71-2.5.3.2.el6_6.x86_64
=> map support

pom.xml
1. Do not attempt to create `/usr/bin` directory to avoid conflict with `filesystem` package on RHEL7 / CentOS7. See #176 (fixed the same problem for ant build).
2. Include `tools` directory with `yaml2jmxtrans.py` script.
=> Fix rpm build

tools/yaml2jmxtrans.py
This recent feature is missing from `yaml2jmxtrans.py` script.
=> Add allowDottedKeys option to config converter

.travis.yml, pom.xml, src/com/googlecode/jmxtrans/model/output/LibratoWriter.java, test/com/googlecode/jmxtrans/model/output/LibratoWriterTest.java, travis-script.sh
This fixes, closes issue #221 . 
We have both log4j and logback jars and looks like slf4j is hitting logback jar first(as classloader seems to be loading those before log4j). In this case logback ignore log4j.xml and uses default configuration where it spits out everything to console. Default console logger is synchronous and hence it could be performance issue as well if we are logging too much.
Logback has really cool features like ability to change log level at runtime using JMX (which is available in log4j2 but not in log4j)
I have put together logback.xml to mimic intending log configuration we were trying to achieve using log4j.xml, with some more added features like automatically delete log file more than 15 days old.
=> Fix logging issues

README.md
There is quite a few interesting information on the Maven generated site. It seems to me that it make sense to improve its visibility.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/232?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/232'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Adding link to maven site

jmxtrans.sh, src/deb/control/postinst
Note that package installation was creating default values for those options, so this has been removed as well to keep coherence.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/238?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/238'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Removed GC optimization to fix #236

src/com/googlecode/jmxtrans/model/naming/KeyUtils.java, src/com/googlecode/jmxtrans/model/output/LibratoWriter.java, test/com/googlecode/jmxtrans/model/output/GraphiteWriterTests.java
I noticed that the AllowDotted property was not being used consistently. Made a change so it is always used by Output classes that use the KeyUtils class.
I think it helps clean up the code a bit but also it's nice to have the AllowDotted property working when outputting graphite data.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/lookfirst%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/85355%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/266%23issuecomment-92475163%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-04-13T19%3A44%3A54Z%22%2C%20%22user%22%3A%20%7B%2 …
=> Cleanup allow dotted

src/com/googlecode/jmxtrans/model/output/OpenTSDBWriter.java
Added debug statement.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/270%23issuecomment-93022069%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/270%23discussion_r28359583%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/270%23discussion_r28359602%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/270%23discussion_r28363676%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/270%23issuecomment-93054183%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/270%23discussion_r28372111%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/270%23discussion_r28372288%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/270%23discussion_r28374038%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/2 …
=> Debug Statement to address issue #269

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Server.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/model/ServerTests.java
fix issue where the port field in the json file was never resolved if a variable was used. (like ${myportnumber}).
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/301%23issuecomment-107375893%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/301%23issuecomment-107375958%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/301%23discussion_r31409701%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/301%23discussion_r31413048%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/301%23discussion_r31426970%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/301%23discussion_r31427079%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/301%23discussion_r31427130%22%5D%2C%20%22comments%22%3A%20%7B%22General …
=> fixed issue with variable resolvement in json file for port field.

jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/OpenTSDBWriter.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/TCollectorUDPWriter.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/OpenTSDBWriterTests.java
And eliminate LifecycleExceptions where possible.
Most of the code and tests is borrowed from GraphiteWriter that trust connection handling to GenericKeyedObjectPool. Prior implementation was throwing LifecycleExceptions on innocent things like refused connections.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/300%23issuecomment-107332031%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/300%23issuecomment-107678333%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/300%23discussion_r31403460%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/300%23discussion_r31403569%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/300%23discussion_r31403607%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/30 …
=> Switch OpenTSDB telnet writer to use GenericKeyedObjectPool

jmxtrans/tools/yaml2jmxtrans.py
Normally, JMXTrans uses the Java Class to name the MBean in the output. Using useObjDomainAsKey will force it to use the MBean name instead.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/312%23issuecomment-118047949%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-07-02T14%3A18%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2315631%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tewner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%3Agun%3A%22%2C%20%22created_at%22%3A%20%222015-07-02T14%3A19%3A14Z%22%2C%20%22user%22%3 …
=> Support the "useObjDomainAsKey" flag in YAML

jmxtrans/src/deb/control/preinst
As jmxtrans is deamon user, it should not have its home directory
under /home/jmxtrans. This commit changes it to /usr/share/jmxtrans,
the same as in rpm version.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/319?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/319'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Changing jmxtrans user home dir in deb packages

pom.xml
Java 8 has enabled DocLint feature by default which causes jmxtrans
build failure. This commit adds -Xdoclint:none param to maven-javadoc
plugin configuration when build is invoked for java versions higher
than 8.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/318%23issuecomment-129845400%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/318%23issuecomment-129847535%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/318%23issuecomment-129847709%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/318%23discussion_r36734351%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/318%23discussion_r36735999%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.c …
=> Disabling JavaDoc DocLint feature

jmxtrans-core/pom.xml, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/jobs/ServerJob.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Server.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/model/ServerTests.java, jmxtrans-examples/src/main/java/com/googlecode/jmxtrans/example/Local.java, jmxtrans-examples/src/main/resources/local.json, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/OpenTSDBWriterTests.java, pom.xml
This patch allow jmxtrans to connect to a local process using its PID.  This is useful if you want to have a local jmxtrans but don't want to embed it or use a java agent.
I've noticed 2 things  that I want to raise to your attention:
* Writer tend to use the server and port in their messages. Those are null in my case. However, they also must be null when jmxtrans is embedded. It seems that jmxtrans-embedded has its own writer. We could probably mutualize them by adding a Server.getIdentity method
* tools.jar must be in the classpath to make it works. An attempt to add it can probably be done in the jmxtrans.sh script
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/323%23discussion_r37627417%22%2C%20%22https%3A//github. …
=> Allow to connect to a local PID

jmxtrans/pom.xml, pom.xml
I simply added an if statement to check redhat version in %pre phase.
I have also added another variable to pom.xml to prevent dollar escape (I usually use it in archetype creation).
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/326%23discussion_r38304284%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/326%23issuecomment-136347717%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/326%23discussion_r38304774%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/326%23discussion_r38312907%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/326%23discussion_r38316415%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/326%23issuecomment-136401141%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/326 …
=> Fixed useradd on redhat release less then or equal RHEL5

jmxtrans/pom.xml
when installing on clean CentOS-7.x, I encountered the following:
/var/tmp/rpm-tmp.OICFi5: line 4: lsb_release: command not found
/var/tmp/rpm-tmp.OICFi5: line 5: [: -gt: unary operator expected
so, I suggest to add lsb_release as requirement
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/327?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/327'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> CentOS-7.X fix

jmxtrans/pom.xml, pom.xml
I have removed fixed guid/uid number, letting system decide.
A problem could happend though, during an upgrade: already created folder could not be updated, if guid/uid is different from the previous one.
The %pre script still checks for RHEL5, otherwise uses default script for everything else.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/328?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/328'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fixed Suse groupadd/useradd

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/jmx/JmxResultProcessor.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/jmx/JmxResultProcessorTest.java
Recently merged #337 makes much more sense if we preserve the original order properties (a.k.a. type name values). It seems that nothing depends on the fact that they are sorted lexicographically, so we may change that behaviour and stick to the original order. That is what JConsole/VisualVM seem to be doing and the point of `useAllTypeNames` was to support  "construct the same tree I see in JConsole/VisualVM in Graphite" out of the box.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/338%23issuecomment-147488424%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/338%23issuecomment-147488424%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%2 …
=> preserve properties order

jmxtrans/doc/tools/yaml2jmxtrans-example.yaml, jmxtrans/tools/yaml2jmxtrans.py
I added support for default query attributes in YAML configuration.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/347%23issuecomment-151883703%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/347%23issuecomment-151883703%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Looks%20good%20to%20me.%5Cr%5Cn%5Cr%5CnCould%20you%20add%20an%20example%20into%20https%3A//github.com/jmxtrans/jmxtrans/tree/master/jmxtrans/doc/tools%20%3F%22%2C%20%22created_at%22%3A%20%222015-10-28T15%3A32%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415765%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//gith …
=> added query_defaults feature to yaml2jmxtrans.py

jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/GraphiteWriter2.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/GraphiteWriterFactory.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/SensuWriter2.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/SensuWriterFactory.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/SensuWriter2Test.java
Minor refactoring to GraphiteWriter2
Sensu writer uses the Graphite format, so it should reuse the GraphiteOutputWriter
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/356?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/356'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Sensu writer now uses TcpOutputWriter

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Server.java, jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriter.java
=> Use 'alias' when provided, don't send NaN values.

jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriter.java, jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriter.java, jmxtrans-output/jmxtrans-output-kafka/src/test/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriterTests.java
Support for adding arbitrary tags to the JSON output generated by the Kafka output writer.  Operates in similar fashion to the OpenTSDB output writer.
Also updating InfluxDB writer to set _jmx_port as a tag instead of field, per [open issue #371] (https://github.com/jmxtrans/jmxtrans/issues/371).
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/377%23issuecomment-165876734%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/377%23issuecomment-165888936%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/377%23discussion_r48059830%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/377%23discussion_r48060858%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/377%23discussion_r48064475%22%2C%20%22https%3A//gith …
=> Tag support for Kafka output writer, use tag instead of field for _jmx_port influxdb output writer

jmxtrans-output/jmxtrans-output-cloudwatch/pom.xml, jmxtrans-output/jmxtrans-output-cloudwatch/src/main/java/com/googlecode/jmxtrans/model/output/CloudWatchWriter.java, jmxtrans-output/jmxtrans-output-cloudwatch/src/test/java/com/googlecode/jmxtrans/model/output/CloudWatchWriterTests.java, jmxtrans-output/jmxtrans-output-cloudwatch/src/test/resources/cloud-watch.json, jmxtrans-output/jmxtrans-output-core/pom.xml
New PR to replace #373.
This patchset adds dimensions to the posted metrics in CloudWatch.
This allows to differ between different instances posting the same metrics.
For ease of deployment, EC2 metadata templates are supported from com.amazonaws.util.EC2MetadataUtils:
{
"obj":"net.sf.ehcache:type=CacheStatistics,CacheManager=__DEFAULT__,name=MyCache",
"attr":[
"CacheHits",
"CacheMisses",
"ObjectCount"
],
"resultAlias":"EHCache",
"outputWriters":[
{
"@class":"com.googlecode.jmxtrans.model.output.CloudWatchWriter",
"settings":{
"namespace":"jmxtrans",
"dimensions":[
{
"name":"Cache",
"value":"MyCache"
},
{
"name":"InstanceId",
"value":"$InstanceId"
}
]
}
}
]
}
Supported EC2 meta values are:
$PublicKey
$AmiId
$AmiLaunchIndex
$AmiManifestPath
$AncestorAmiIds
$InstanceAction
$InstanceId …
=> Add dimensions to Metrics

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Query.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/naming/typename/TypeNameValuesStringBuilder.java, jmxtrans-output/jmxtrans-output-jrobin/src/main/java/com/googlecode/jmxtrans/model/output/RRDToolWriter.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1155 - Collection.isEmpty() should be used to test for emptiness
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1155
Please let me know if you have any questions.
Kirill Vlasov
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/391?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/391'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
<a …
=> Collection.isEmpty() should be used to test for emptiness

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/PropertyResolver.java, jmxtrans-output/jmxtrans-output-influxdb/src/test/java/com/googlecode/jmxtrans/model/output/InfluxDbWriterTests.java
This pull request is focused on resolving occurrences of Sonar rules 
squid:S00116 - Field names should comply with a naming convention, 
squid:S3008 - Static non-final field names should comply with a naming convention
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S00116
https://dev.eclipse.org/sonar/coding_rules#q=squid:S3008
Please let me know if you have any questions.
Kirill Vlasov
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/392?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a …
=> Fields modifiers convention fixes

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/output/BaseOutputWriter.java
The idea is to remove settings and replace them by explicit arguments on the output writers. This warning will help user to transition to the new configuration format.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/394?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/394'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> The use of settings is deprecated, warning is logged if it is still used

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/guice/JmxTransModule.java
Each time when a ResultProcessor, JMXTransformer (or other classes
relying on the thread pools) got instantiated, new, fresh thread pools
got created along with it.
Since each instance had their own thread pool, the global thread
number limits was not enforced, and as a result the total, global
thread number increased way beyond the set pool sizes.
(E.g.: Despite a pool limits of 10 for query and 10 for result thread
pools, configuring jmxtrans to do a single query each 3 seconds gave
2000 active threads within 50 minutes.)
By turning the thread pools into singletons, Guice takes care of
re-using the existing thread pools and thereby, limits on thread
numbers are enforced.
Fixes #401
<a href='https://www.codereviewhub.com/'><img …
=> Re-use thread pool to enforce global thread limits

README.md
Unstable builds were hard to find, as they were not linked in the
docs. By adding them to the README, we make sure people are aware that
they do not need to run their own builds if they want to run bleeding
edge.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/403?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/403'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Link unstable builds in README

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Server.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/model/ServerTests.java
If a JMXConnection fails at some point (E.g.: JMX providing JVM dies),
the JMXConnection gets invalidated. Previously, we then tried to
re-pool this failed Connection. By keeping failed Connections in the
pool, future queries will again re-use the failed, pooled connection,
and again fail and re-pool the Connection. This behaviour effectively
means that if some JMX providing JVM is temporarily unavailable (e.g.:
gets restarted), jmxtrans stops getting metrics from it, even if the
JVM comes back, as jmxtrans is stuck on the failed, pooled
connections.
Hence, we no longer re-pool failed connections. Thereby, we try to
reconnect upon the next run, and will eventually start picking up
metrics from JMX providing JVMs once they come back.
Fixes #399
<a href='#crh-start'></a><a …
=> Stop re-pooling failed JMXConnections

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/jmx/JmxUtils.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/jmx/ProcessQueryThread.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/jmx/ResultProcessor.java
If an executor service rejects an execution (all threads busy and work queue full) an error message is sent to the logs.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/409?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/409'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Add error message on rejected execution

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/naming/JexlNamingStrategy.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/OpenTSDBGenericWriter.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/OpenTSDBWriter.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/OpenTSDBWriter2.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/OpenTSDBWriterFactory.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/TCollectorUDPWriter.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/TCollectorUDPWriter2.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/TCollectorUDPWriterFactory.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/support/opentsdb/OpenTSDBMessageFormatter.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/OpenTSDBGenericWriterTests.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/OpenTSDBWriter2Test.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/TCollectorUDPWriter2Test.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/support/opentsdb/OpenTSDBMessageFormatterTest.java
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/413%23discussion_r50539851%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/413%23discussion_r50539931%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/413%23discussion_r50540051%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/413%23discussion_r50540158%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/413%23discussion_r50540293%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/413%23discussion_r50540377%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/413%23discussion_r50540475%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/413%23discussion_r50540517%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/413%23discussion_r50540538 …
=> use standard tcp and udp writer for OpenTSDB

jmxtrans-core/pom.xml, jmxtrans-examples/pom.xml, jmxtrans-output/jmxtrans-output-cloudwatch/pom.xml, jmxtrans-output/jmxtrans-output-core/pom.xml, jmxtrans-output/jmxtrans-output-ganglia/pom.xml, jmxtrans-output/jmxtrans-output-influxdb/pom.xml, jmxtrans-output/jmxtrans-output-jrobin/pom.xml, jmxtrans-output/jmxtrans-output-log4j/pom.xml, jmxtrans-output/jmxtrans-output-velocity/pom.xml, jmxtrans-output/pom.xml, jmxtrans-test-utils/pom.xml, jmxtrans-utils/pom.xml, jmxtrans/pom.xml, pom.xml
This is basically a reimplementation of #299. This should be more stable (and more standard) than the Maven GitHub plugins.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/414?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/414'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Now uses scm-publish to upload maven site

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/guice/JmxTransModule.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Server.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/JmxTransformerIT.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/JmxTransformerTest.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/model/ServerTests.java, pom.xml
Fixes for #419 
Jackson doesn't seem to properly handle generics so it won't find any `TypeLiteral` bindings.  I refactored this to use an explicit binding with a @Named parameter.
The `JmxTransfomerIT` test wasn't running as part of the build (and would have caught this) so I renamed it to to actually run during the build.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/420%23discussion_r51572466%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/420%23issuecomment-178777648%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/420%23issuecomment-178812723%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/420%23discussion_r51637222%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/420%23discussion_r516373 …
=> #419 Refactor guice config for Server

.travis.yml, jmxtrans-docker-test/pom.xml, jmxtrans-docker-test/src/main/docker/assembly-docker.xml, jmxtrans-docker-test/src/main/docker/localhost.json, jmxtrans-docker-test/src/main/docker/verify.sh, jmxtrans/pom.xml, pom.xml, travis-script.sh
@gehel this PR adds a new maven module that spins up docker images for various linux distributions to test the RPM & deb packages.
It is not complete yet but I'm unable to test it in my fork due to the missing GPG information.  I'm hoping that creating the PR here will successfully run the build with your travis config.  
I'll update the PR when the testing is complete.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/423%23issuecomment-183488379%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/423%23issuecomment-183495072%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/423%23issuecomment-183495541%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/423%23issuecomment-183633758%22%2C%20%22https%3A//github. …
=> Verify RPM/Deb Behavior with Docker Tests

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/ServerListBuilder.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/SingletonOutputWriterFactory.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/ServerListBuilderTest.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/model/SingletonOutputWriterFactoryTest.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/GraphiteWriterTests.java
as pointed out in #432.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/435?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/435'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Correct issue with multiple instances of output writers being created

jmxtrans-core/pom.xml, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/GraphiteWriterFactory.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/OpenTSDBWriterFactory.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/SensuWriterFactory.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StatsDWriterFactory.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/TCollectorUDPWriterFactory.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/StatsDWriterFactoryIT.java
Introduce a `poolSize` parameters on OutputWriter that use a TCP or UDP pool.
The pool used for those output writers is stormpot [1]. Have a look at its
documentation [2] for details.
This fixes #432.
[1] https://github.com/chrisvest/stormpot
[2] http://chrisvest.github.io/stormpot/site/apidocs/stormpot/Config.html
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/436?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/436'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
<a …
=> Make XXXWriter Pool configurable

jmxtrans-core/pom.xml, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/JHadesIT.java, jmxtrans-examples/pom.xml, jmxtrans-examples/src/test/java/com/googlecode/jmxtrans/example/JHadesIT.java, jmxtrans-output/jmxtrans-output-cloudwatch/src/test/java/com/googlecode/jmxtrans/model/output/JHadesIT.java, jmxtrans-output/jmxtrans-output-core/pom.xml, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/JHadesIT.java, jmxtrans-output/jmxtrans-output-elastic/pom.xml, jmxtrans-output/jmxtrans-output-elastic/src/test/java/com/googlecode/jmxtrans/model/output/elastic/JHadesIT.java, jmxtrans-output/jmxtrans-output-ganglia/src/test/java/com/googlecode/jmxtrans/model/output/JHadesIT.java, jmxtrans-output/jmxtrans-output-influxdb/pom.xml, jmxtrans-output/jmxtrans-output-influxdb/src/test/java/com/googlecode/jmxtrans/model/output/JHadesIT.java, jmxtrans-output/jmxtrans-output-jrobin/pom.xml, jmxtrans-output/jmxtrans-output-jrobin/src/test/java/com/googlecode/jmxtrans/model/output/JHadesIT.java, jmxtrans-output/jmxtrans-output-kafka/pom.xml, jmxtrans-output/jmxtrans-output-kafka/src/test/java/com/googlecode/jmxtrans/model/output/kafka/JHadesIT.java, jmxtrans-output/jmxtrans-output-log4j/pom.xml, jmxtrans-output/jmxtrans-output-log4j/src/test/java/com/googlecode/jmxtrans/model/output/JHadesIT.java, jmxtrans-output/jmxtrans-output-velocity/pom.xml, jmxtrans-output/jmxtrans-output-velocity/src/test/java/com/googlecode/jmxtrans/model/output/JHadesIT.java, jmxtrans-test-utils/pom.xml, jmxtrans-test-utils/src/main/java/com/googlecode/jmxtrans/test/JHadesBaseTest.java, jmxtrans-test-utils/src/test/java/com/googlecode/jmxtrans/test/JHadesIT.java, jmxtrans-utils/src/test/java/com/googlecode/jmxtrans/util/JHadesIT.java, jmxtrans/pom.xml, jmxtrans/src/test/java/com/googlecode/jmxtrans/JHadesIT.java, pom.xml
JHades helps find classpath inconsistencies (and we still have few). JHades
is run as a test case. It does not actually fail the build, but prints
interesting information.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/437?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/437'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Added JHades as a test case.

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/JmxTransformer.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/cli/JmxTransConfiguration.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/JmxTransformerTest.java
Instead of querying averything at the 60 second mark (or whatever the
runPeriod is), spread them a bit.
Also increased the queue size of executor services to something more
reasonnable.
This should fix #443.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/444?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/444'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Spread queries over time

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/ResultFixtures.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StatsDWriter.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StatsDWriter2.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/StatsDWriter2Test.java
This fixes #448 in the same way it was fixed in #272.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/449?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/449'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Truncate double values below C precision to zero

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Query.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/model/QueryTests.java
Storing `typeNames` as `Set` matches the fact that "key properties" of
an `ObjectName` are an unordered set [0]. But for `ObjectName`s like
org.apache.cassandra.db:type=ColumnFamilies,keyspace=foo,columnfamily=bar
and `typeNames` of `["keyspace", "columnfamily"]`, the set nature gets
in the way, as it is unpredictable whether metrics will get reported
as `foo_bar`, or `bar_foo`. To avoid such issues, we store `typeNames`
in the order specified by the user. That way, we can provide
predictable names that matches user's preference.
Since such a change may affect downstream users, we're still exposing
the methods for typeName sets, but we deprecated them in favor of list
variants.
Fixes #463
[0] http://docs.oracle.com/javase/7/docs/api/javax/management/ObjectName.html
<a …
=> Change Query's typeNames from Set to List

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Server.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/model/ServerTests.java
When an error occurs during execution of a JMX query, the JMXConnection object is invalidated in the pool. This means that future queries will not reuse the existing JMXConnection, rather creating a new one.
We should ensure that the JMXConnection is closed before invalidating/discarding it in order to avoid resource leaks.
There is no knowledge about the original query error, which means that the JMXConnection may be in an invalid state. Hence just ignore and log any exceptions that may be thrown when we try to close it on error.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/470?approve=1'><img …
=> Close invalidated JMX Connection when query execution fails.

jmxtrans/jmxtrans.sh
sysvinit initscript starts jmxtrans.sh under `/usr/share/jmxtrans`
so the default `JAR_FILE` location should be set relative to that
path: `/usr/share/jmxtrans/lib/jmxtrans-all.jar`
Usually `/etc/default/jmxtrans` sets `JAR_FILE` so it is shadowing the
default location bug.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/469%23issuecomment-225429602%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/469%23issuecomment-225429602%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Thanks%20for%20the%20fix%21%22%2C%20%22created_at%22%3A%20%222016-06-12T12%3A25%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubu …
=> Fix default jmxtrans-all.jar location

jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriter.java, jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriterFactory.java, jmxtrans-output/jmxtrans-output-influxdb/src/test/java/com/googlecode/jmxtrans/model/output/InfluxDbWriterTests.java, jmxtrans-output/jmxtrans-output-influxdb/src/test/resources/influxDB.json
A simple Hasmap<String ,String> added to the influxDbFactory JSON descriptor, in order to add custom tags to an influxDB record.
Use case : I have a Kubernetes cluster with many app, replicated across the cluster.
My cluster is monitored  by heapster, InfluxDb and grafana.
I can easily monitor every single pod with the 'podname' var ( ie hostname in jmxTrans ), but i can't group by appName afaik.
I needed to write those customs tags to influxDB to be able to group by Application Name and not only by podname (which, by the way, change every time you redeploy or restart an app. I ended up with more than 50 different values of "podname" with almost 60% of them was stopped a long time ago).
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/ …
=>  Add custom tags to influxDbWriter

jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/support/WriterPoolOutputWriter.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/support/pool/WriterPoolable.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/support/WriterPoolOutputWriterTest.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/support/pool/WriterPoolableTest.java
@gehel fixes for #479 in this PR.
Also included a related fix for an NPE that occurs when the request to claim a writer from the pool times out.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/480?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/480'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Issue #479 - Add better handling for pool timeouts and errors during slot release

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/JmxTransformer.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/output/support/ResultTransformerOutputWriter.java
This PR addresses #500 to fix cleanup of singleton output writers along with implementing a stop() method on ResultTransformerOutputWriter.  See issue #500 for additional details.
=> Singleton OutputWriter cleanup, implement stop() on ResultTransformerOutputWriter

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/ResultFixtures.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/ServerFixtures.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StatsDMetricType.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StatsDTelegrafWriter.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StatsDTelegrafWriterFactory.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/GraphiteWriterTests.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/LibratoWriter2Test.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/LibratoWriterFactoryIT.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/OpenTSDBWriterTests.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/Slf4JOutputWriterTest.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/StatsDTelegrafWriterTest.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/StatsDWriter2Test.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/StatsDWriterFactoryIT.java, jmxtrans-output/jmxtrans-output-kafka/src/test/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriterTests.java
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/501%23issuecomment-255544502%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/501%23issuecomment-255544630%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/501%23issuecomment-255681107%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/501%23issuecomment-255682396%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/501%23issuecomment-255699713%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/501%23discussion_r84665578%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/501%23discussion_r84677161%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/501%23discussion_r84677752%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22ht …
=> Added new StatsDTelegrafWriter to support JMX attributes as tags

jmxtrans/tools/yaml2jmxtrans.py
As of https://www.python.org/dev/peps/pep-0263/, magic comment must be the first or the second line of the file. Also, copyright symbol in license is UTF-8.
```
File "/usr/share/jmxtrans/tools/yaml2jmxtrans.py", line 4
SyntaxError: Non-ASCII character '\xc2' in file /usr/share/jmxtrans/tools/yaml2jmxtrans.py on line 4, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```
=> Fix encoding declaration in Python code

jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriterFactory.java, pom.xml
This uses the latest version of influxdb-java (2.4) to support connecting to InfluxDB 1.0. 
This also changes the default retention policy from "default" to "autogen"
This is a breaking change for anyone relying on the old defaults.
Resolves errors:
```sh
ava.lang.RuntimeException: {"error":"error parsing query: found NOT, expected ; at line 1, char 20"}
```
and 
```sh
java.lang.RuntimeException: {"error":"retention policy not found: default"}
```
As mentioned in:
https://github.com/jmxtrans/jmxtrans/issues/489
=> Allow InfluxDBWriter to connect to 1.0 out of the box

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Server.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/model/ServerTests.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/OpenTSDBGenericWriter.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/OpenTSDBWriter.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/OpenTSDBWriter2.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/OpenTSDBWriterFactory.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/TCollectorUDPWriter.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/TCollectorUDPWriter2.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/TCollectorUDPWriterFactory.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/support/opentsdb/OpenTSDBMessageFormatter.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/OpenTSDBGenericWriterTests.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/OpenTSDBWriter2Test.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/OpenTSDBWriterTests.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/TCollectorUDPWriter2Test.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/TCollectorUDPWriterTests.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/support/opentsdb/OpenTSDBMessageFormatterTest.java
Added a default for mergeTypeNamesTags to match the docs as well as added a null check against typeNames since that item is supposed to be optional.
Made more changes to move around Server through OpenTSDBMessageFormatter and removed a couple getHostName() calls so that only Server resolves the hostname.  The property on outputWriters in the configuration now stays as a boolean value throughout.  Little larger change than the initial but tests for OpenTSDBWriter* and TCollectorUDPWriter* pass with the new configuration.
=> null check and defaults added

jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/FileWriter.java
This makes it possible for a file to hold the latest metrics results for a given a given query.
The major difference between this and the `KeyOutWriter` is that the file will represent the most update-to-date state of the metrics results.
=> Implement simple FileWriter for unopinionated interoperability

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/ResultFixtures.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StatsDWriter2.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/StatsDWriter2Test.java
This is a follow up to #530 that handles the null value side effect of that change.
=> Properly convert NaN/null values to empty value in StatsDWriter2

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/ResultFixtures.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/GraphiteWriter.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/GraphiteWriter2.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/GraphiteWriter2Test.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/GraphiteWriterTests.java, jmxtrans-utils/src/main/java/com/googlecode/jmxtrans/util/NumberUtils.java, jmxtrans-utils/src/test/java/com/googlecode/jmxtrans/util/NumberUtilsTest.java
@gehel This PR fixes the issue reported in #539 
I added a utility method `isValidNumber` that ensures that the number is not NaN or infinity.
=> Issue #539 Skip invalid "numbers" when reporting to graphite

jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/FileWriter.java
After running this for a while, I realised that `StandardCopyOption.REPLACE_EXISTING` will not use atomic moves even if they are possible. The `StandardCopyOption.ATOMIC_MOVE` will throw an exception if the underlying OS doesn't support atomic moves.
The `renameTo` function will do an atomic move if possible, and fall back to non-atomic if not possible.
=> FileWriter Atomic Rename Improvement

jmxtrans-output/jmxtrans-output-log4j/src/main/java/com/googlecode/jmxtrans/model/output/DailyKeyOutWriter.java, jmxtrans-output/jmxtrans-output-log4j/src/main/java/com/googlecode/jmxtrans/model/output/KeyOutWriter.java, jmxtrans-output/jmxtrans-output-log4j/src/main/java/com/googlecode/jmxtrans/model/output/TimeBasedRollingKeyOutWriter.java
- Change type in constructor from `int` to `Integer`.
This fixes #559.
=> Ensure KeyOutWriter, DailyKeyOutWriter, and TimeBasedRollingKeyOutWriter populate maxLogBackupFiles correctly.

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/naming/KeyUtils.java, jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriter.java, jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriterFactory.java, jmxtrans-output/jmxtrans-output-influxdb/src/test/java/com/googlecode/jmxtrans/model/output/InfluxDbWriterTests.java
Currently when using wildcards with influxdb output writer it does not use the specified typeNames at all, which causes non-unique names and errors.   Update to use typeNames properly, they are prepended to the key name to make a unique key.
=> 567 - fix influx output writer to properly use typeNames 

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/output/support/ResultTransformerOutputWriter.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/GraphiteWriterFactory.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/support/TcpOutputWriterBuilder.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/support/UdpOutputWriterBuilder.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/support/WriterPoolOutputWriter.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/support/GraphiteWriterFactoryTest.java, jmxtrans-output/jmxtrans-output-core/src/test/resources/graphite-writer-factory-example-with-udp.json, jmxtrans-output/jmxtrans-output-core/src/test/resources/graphite-writer-factory-example2.json
Hello,
I'm in the case where i have a central graphite server for all my datacenter (US, EU and APAC). I have seen that there is a hard coded value (200ms) on socket timeout and this PR will allow to set some additional settings for socket timeout and pool claim timeout. This add the possibility to use the UdpOutputWriter instead of the TcpOutputWriter (udp vs tcp).
I have deploy this version in production to fix the issue. I don't find where you generate the documentation to add some details for these new settings.
Some configuration examples:
```
"outputWriters" : [ {
"@class" : "com.googlecode.jmxtrans.model.output.GraphiteWriterFactory",
"port" : 2003,
"host" : "your_host",
"protocol" : "udp",
"poolClaimTimeoutSeconds" : 2
} ]
```
```
"outputWriters" : [ {
"@class" : …
```
=> Add socket timeout settings and udp support for graphite writer

jmxtrans/src/deb/control/postinst
On Ubuntu/Debian, the default log level is DEBUG, which I think is too verbose. Most user don't need debug level, and if needed it's easy to change the default on their setup.
My log file is about 700Mb per day (I don't monitor lots of metrics - about 26 metrics, but I do it every 10 seconds).
This PR change the default on .deb package from DEBUG to INFO.
Note: .rpm package are already at info level
=> Change default log level to INFO

jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/SensuWriter2Test.java, jmxtrans-test-utils/src/main/java/com/googlecode/jmxtrans/test/MonitorableApp.java
Build fails on Windows due to differences with:
* File path separator and file separator
```
Running com.googlecode.jmxtrans.JmxTransformerIT
Erreur : impossible de trouver ou charger la classe principale com.googlecode.jmxtrans.test.DummyApp
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.135 sec <<< FAILURE! - in com.googlecode.jmxtrans.JmxTransformerIT
metricsAreSentToStdout(com.googlecode.jmxtrans.JmxTransformerIT)  Time elapsed: 7.135 sec  <<< ERROR!
com.jayway.awaitility.core.ConditionTimeoutException: Condition returned by method "hasLineContaining" in class com.googlecode.jmxtrans.test.OutputCapture was not fulfilled within 5 seconds.
at com.googlecode.jmxtrans.JmxTransformerIT.metricsAreSentToStdout(JmxTransformerIT.java:67)
Results :
Tests in error: …
```
=> Fix tests on Windows

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Result.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/ResultAttribute.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/ResultAttributes.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/model/ResultAttributeTests.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StatsDTelegrafWriterFactory.java, jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriter.java, jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriterFactory.java, jmxtrans-output/jmxtrans-output-influxdb/src/test/java/com/googlecode/jmxtrans/model/output/InfluxDbWriterTests.java, jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/DefaultResultSerializer.java, jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/DetailedResultSerializer.java, jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriter.java, jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriterFactory.java, jmxtrans-output/jmxtrans-output-kafka/src/test/java/com/googlecode/jmxtrans/model/output/kafka/DefaultResultSerializerTest.java, jmxtrans-output/jmxtrans-output-kafka/src/test/java/com/googlecode/jmxtrans/model/output/kafka/DetailedResultSerializerTest.java
* Add getTypeNameMap in Result and use it to detail DetailedResultSerializer
* Add ResultAttribute implementation to get typeName props and use it in DefaultResultSerializer, InfluxdbWriter and StatsdWriter
* Split ResultAttribute enum into ResultAttribute class + ResultAttributes factory
* Replace reflection by pure method calls (with Java 8 lambdas code could be even simpler)
=> Make typeName properties individually accessible

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/results/CPrecisionValueTransformer.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/model/results/CPrecisionValueTransformerTests.java
fix for #615 
CPercisionValueTransformer now returns null if input is infinite
=> Handle infinity in CPercisionValueTransformer

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/ResultFixtures.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/output/BaseOutputWriter.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StatsDWriter.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StatsDWriter2.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StatsDWriterFactory.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/StatsDWriter2Test.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/StatsDWriterFactoryIT.java
It is possible for JMX to have characters invalid for statsd. This causes to parsing to become incorrect.
The unit test added is what we are seeing, where the scope can have "127.0.0.1:8080" where statsd uses the colon as a delimiter between the key and value.
I added an option "invalidCharValue" so that it can be customized.
=> Replace illegal statsd characters.

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Server.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/util/ProcessConfigUtils.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/model/ServerTests.java
My collegue wrote (https://gitter.im/jmxtrans/jmxtrans?at=58e4fdaaad849bcf425405a5)
> Hi! I’m observing a strange side effect when using jmxtrans (build 260) to collect metrics from Cassandra nodes. When at least one node is down, I observe incorrect or missing datapoints on all other metrics coming from the same instance of jmxtrans.
What am I doing wrong?
We've tried to fix this. But I have no idea what's wrong.
There are my investigation results. May be it helps to get answer.
First of all we've covered by logs next methods
- Server.execute
- JmxUtils.processServer
After that we're replayed this scenario at production. One cassandra node was closed by firewall to test instance of jmxtrans.
What actually happened.
Logs from JmxUtils.processServer when we closed node by firewall and our …
=> Collecting metrics stops when at least one node is down

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/connections/JMXConnection.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/connections/MBeanServerConnectionFactory.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/guice/JmxTransModule.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/JmxTransRMIClientSocketFactory.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Server.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/JmxTransformerTest.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/connections/MBeanServerConnectionFactoryTest.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/model/JMXConnectionTest.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/model/ServerTests.java
JMXConnector works slowly when server unavailable and executor thread pool fills up quickly. This changes can reduce awaiting duration.
This fixes refers to https://github.com/jmxtrans/jmxtrans/issues/626
=> JMXConnector works slowly when server unavailable

jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriter.java, jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriterFactory.java, jmxtrans-output/jmxtrans-output-influxdb/src/test/java/com/googlecode/jmxtrans/model/output/InfluxDbWriterTests.java, jmxtrans-output/jmxtrans-output-influxdb/src/test/resources/influxDB.json
Add a property "reportJmxPortAsTag" to InfluxDbWriter allowing users to specify if the JMX port is written as a field (current and default behavior) or as a tag (cf. issue #371).
=> InfluxDb output : allowing to report JMX port as a tag

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/JmxTransformer.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/cli/JmxTransConfiguration.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/executors/CommonExecutorRepository.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/executors/ExecutorFactory.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/executors/ExecutorRepository.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/executors/SeparateExecutorRepository.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/guice/JmxTransModule.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/jmx/JmxUtils.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/jmx/ResultProcessor.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Server.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/monitoring/ManagedThreadPoolExecutor.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/JmxTransformerTest.java
As I mentioned at https://github.com/jmxtrans/jmxtrans/issues/626 I found trouble behavior with common thread pool. For backward compatibility I implemented it though another strategy. I've tried it on production and it works. Dead server didn't affect another servers.
In future it can be extended. Server config may contain executor settings for each server.
=> Separate thread pool executors

jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/GraphiteWriterFactory.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/support/TcpOutputWriterBuilder.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/support/UdpOutputWriterBuilder.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/support/DummySequenceWriterBasedOutputWriter.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/support/GraphiteWriterFactoryTest.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/support/TcpOutputWriterBuilderIT.java, jmxtrans-output/jmxtrans-output-core/src/test/resources/graphite-writer-factory-example-with-timed-socket-expiration.json, jmxtrans-test-utils/src/main/java/com/googlecode/jmxtrans/test/TCPEchoServer.java
This adds an optional socket expiration timeout for `GraphiteWriterFactory`, which is useful if your graphite host is behind a load balancer that does not support indefinite idle connections, for example AWS classic ELB.
=> Added optional time socket expiration for GraphiteWriterFactory.

appveyor.yml, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/output/KeyValueResultSerializer.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/output/ResultSerializer.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/output/StdOutWriter.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/output/ToStringResultSerializer.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/model/output/KeyValueResultSerializerTest.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/model/output/StdOutWriterTest.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/model/output/ToStringResultSerializerTest.java, jmxtrans-examples/src/main/java/com/googlecode/jmxtrans/example/InterestingInfo.java, jmxtrans-examples/src/main/java/com/googlecode/jmxtrans/example/Tester.java, jmxtrans-examples/src/main/java/com/googlecode/jmxtrans/example/TreeWalker2.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/FileWriter.java, jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/Slf4JOutputWriter.java, jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/Slf4JOutputWriterTest.java, jmxtrans-output/jmxtrans-output-kafka/pom.xml, jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/DefaultResultSerializer.java, jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/DetailedResultSerializer.java, jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriter.java, jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriter2.java, jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriterFactory.java, jmxtrans-output/jmxtrans-output-kafka/src/test/java/com/googlecode/jmxtrans/model/output/kafka/DefaultResultSerializerTest.java, jmxtrans-output/jmxtrans-output-kafka/src/test/java/com/googlecode/jmxtrans/model/output/kafka/DetailedResultSerializerTest.java, jmxtrans-output/jmxtrans-output-kafka/src/test/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriter2Test.java, jmxtrans-output/jmxtrans-output-kafka/src/test/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriterFactoryTest.java, jmxtrans-output/jmxtrans-output-kafka/src/test/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriterTests.java
Pull this interface in core and use it in many outputwriters: stdout, file, slf4j, kafka...
Removing code in the Kafka output, I add to add test and refactor a bit to satisfy mutation testing.
=> Generalize ResultSerializer 

jmxtrans-packaging/jmxtrans-systemd/src/etc/jmxtrans
Fixed deb / systemd start script to pick up the log4j configuration.
The logs could be viewed with:
* `journalctl -u jmxtrans.service`
* `/var/log/jmxtrans/jmxtrans.log`
=> Fixed deb / systemd start script to pick up the log4j configuration.

jmxtrans-output/jmxtrans-output-logback/pom.xml, jmxtrans-output/jmxtrans-output-logback/src/main/java/com/googlecode/jmxtrans/model/output/KeyOutWriter.java
Graphite plaintext protocol uses a timestamp in secondes, but the writer writes this timestamp in ms. I just divided the value by 1000 to fit the protocol.
=> Fixed : Timestamp in milliseconds

jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriter.java, jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriterFactory.java, jmxtrans-output/jmxtrans-output-influxdb/src/test/java/com/googlecode/jmxtrans/model/output/InfluxDbWriterTests.java
Continuation of the work from #660 with the segregateStringValues parameter (renamed allowStringValues) which allows the InfluxDBWriter to write string fields in InfluxDB.
Additional work was also done: 
- Fix 2 bugs with the typeNames parameter
- Update the tests
- Add description of the InfluxDBWriterFactory parameters
I'm also working on a new parameter for the InfluxDBWriter, called "attributesAsTag": 
In InfluxDB, you can store values as tag or as fields. Tags are indexed, fields not. (See [here](https://docs.influxdata.com/influxdb/v1.5/concepts/key_concepts/).) Actually, the InfluxDbWriter stores every attributes value as fields. If this format is adapted for metrics (counters, averages, etc...), you can have performance issues when reading if you try to filter with them. Tags are …
=> InfluxDB : Allow string values and more

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Server.java
Added the type GetAlias(), which is used by KeyUtils.java (most likely in more places):
https://github.com/jmxtrans/jmxtrans/blob/712b24f4f9e162b8456a15eea87517b5fff9cb66/jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/naming/KeyUtils.java#L97-L106
=> added GetAlias type definition

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/ResultFixtures.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/naming/KeyUtils.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/model/naming/KeyUtilsTest.java
It is often convenient not to have any key prefix but only attribute name.
For instance when storing metrics in CloudWatch Agent via statsd instead of having long metric name:
`coordinator_presto_memory_NonHeapMemoryUsage_used`
I would rather have:
`NonHeapMemoryUsage_used`
as I can identify metric source via so called "dimensions" (statsd attributes).
=> Skip separator when key prefix is empty

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/JmxResultProcessor.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/jmx/JmxResultProcessorTest.java
Keys filtering is useful in cloud environments where one pays
price per metric. In some cases, (e.g: `NonHeapMemoryUsage`) some
keys have meaningless values, so it doesn't make sense to evaluate them
for every machine.
=> Add support for keys filtering to jmx result processor

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/JmxTransformer.java
Reload of configuration fail because MBean is tried to be registered twice (one at startup, then once when scheduleReload call startupSystem).
This regression appear with #629 which moved the MBean initialization from doMain to startupSystem.
This PR move the MBean initialization outside startupSystem to restore old behavior and javadoc of statupSystem.
Note: the exception won't be logged, because #711 moved the actual reloading in a Runnable future and transform the exception in RuntimeException. If you want to see the exception, a log should be added in the try/catch.
* Create directory
```
mkdir -p log conf.d
```
* Create a configuration file (it assume a JVM with JMX on port 7999 is running on localhost):
```
cat > conf.d/config.json << EOF
{
"servers": [
{
"host": "127.0.0.1", …
```
=> Fix configure reload

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/JmxTransformer.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/executors/CommonExecutorRepository.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/executors/ExecutorRepository.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/executors/SeparateExecutorRepository.java
When a file was added/deleted/modified in the watchdir, the reload
would attempt to add the same mbeans to the JmxMBeanServer. This
would cause jmxtrans to hang and the watchdir functionality to be
useless.
Restructured reload to remove stale beans. Also, removes stale
server instances from the executor repositories so the repositories
don't grow unbounded when running with --use-separate-executors.
Possibly related to issue #678.
The exception:
```
javax.management.InstanceAlreadyExistsException: com.googlecode.jmxtrans:Type=JmxTransformerProcess,Name=JmxTransformerProcess
at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
at …
```
=> Preventing InstanceAlreadyExistsException on Reload

jmxtrans-utils/src/main/java/com/googlecode/jmxtrans/classloader/ClassLoaderEnricher.java
SystemClassLoader is not of type URLClassLoader,
as a result additional jar feature doesn't work on recent Java versions.
Fix the error message in that situation.
I wonder whether we shouldn't remove the additional jar option as well.
=> Print simple error message when addition jar on Java 9+

pom.xml
Upgrade influxdb to 2.21 (latest version)
Need upgrade of duplicate-finder-maven-plugin to 1.4.0+ to handle multi-release jars dependencies of influxdb (kotlin-std-lib)
This version of influxDB client uses a newer version of OkHttp which spawns less threads
=> Upgrade InfluxDb-java client

jmxtrans-core/src/main/java/com/googlecode/jmxtrans/ServerListBuilder.java, jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Server.java, jmxtrans-core/src/test/java/com/googlecode/jmxtrans/ServerListBuilderTest.java
Copy the builded outputwriters when building a server from an other one.
Fixes #796
Note that in SeverListBuilder.TemporaryServer.build we clean this copied list in order to use the singleton value of the outputwriters
=> Keep outputwriters in server copy
