- src/com/googlecode/jmxtrans/model/output/GraphiteWriter.java
We found issues using jmxtrans with Graphite where jmxtrans would lose its connection to Graphite and never reconnect. This PR fixes this issue (at least for us).
> Fix for jmxtrans losing connection to Graphite and never reconnecting

- pom.xml
- src/com/googlecode/jmxtrans/model/output/LibratoWriter.java
- test/com/googlecode/jmxtrans/model/output/LibratoWriterTest.java
This fixes #216.
Tests are minimal as no previous unit test existed on this class. New functionalities are mostly tested.
> Added a descriptive user agent to Librato writer.

- pom.xml
add ignore for sortpom
simpler and more coherent fix to go back to log4j logging
> reorder pom with slf4j-log4j12 at top

- src/com/googlecode/jmxtrans/connections/DatagramSocketFactory.java
- test/com/googlecode/jmxtrans/connections/DatagramSocketFactoryTest.java
This is a rebase of #77 (thanks to @Savar and sorry for the delay).
I should write an integration test for the DatagramSocketFactory, but it is fairly clear that the current implementation is broken.
> Fix of datagram socket factory

- src/com/googlecode/jmxtrans/ConfigurationParser.java
- src/com/googlecode/jmxtrans/JmxTransformer.java
- src/com/googlecode/jmxtrans/model/Server.java
- test/com/googlecode/jmxtrans/ConfigurationParserTest.java
Also extracted some of the parsing logic to make it testable.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/241?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/241'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Fix wrong condition in JMXTransformer.processFilesIntoServers(). Fixes #240.

- pom.xml
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/242?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/242'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Updated all dependencies to latest versions.

- pom.xml
- src/com/googlecode/jmxtrans/model/output/CloudWatchWriter.java
- test/com/googlecode/jmxtrans/model/output/CloudWatchWriterTests.java
This replaces #243
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/244?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/244'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Added CloudWatch writer

- pom.xml
- src/com/googlecode/jmxtrans/util/SignalInterceptor.java
This is done by using the animal sniffer plugin.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/245?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/245'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Ensure we keep compatibility with Java6

- pom.xml
- travis-script.sh
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/247?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/247'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Trying to create a first automated release

- pom.xml
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/248?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/248'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Automatic release of Sonatype staging repo

- pom.xml
- travis-script.sh
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/249?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/249'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Trying (again) to automatically create a release

- pom.xml
- travis-script.sh
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/250?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/250'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> debug settings.xml

- travis-script.sh
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/251?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/251'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Removed useless debug of settings

- pom.xml
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/252?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/252'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Add effective pom to release preparation for debugging

- pom.xml
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/253?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/253'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Do not clean during preparation to ensure we keep the checkout of travis branch

- .travis.yml
- travis-script.sh
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/254?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/254'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Move travis branch checkout outside of project hierarchy

- pom.xml
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/255?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/255'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Remove debugging help for settings

- travis-script.sh
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/256?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/256'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Configure git identity as part of the release build

- pom.xml
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/257?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/257'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> ensure pom is sorted after being modified for release

- travis-script.sh
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/258?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/258'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> make sure release is not done on a detatched head

- travis-script.sh
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/259?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/259'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Add SSH key so that we can push changes to GitHub during release

- travis-script.sh
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/260?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/260'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Fix permissions on SSH private key

- travis-script.sh
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/261?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/261'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Fix permissions on SSH private key (again)

- pom.xml
I need to read documentation with more concentration ...
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/262?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/262'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Seems that explicitly releasing the staging repository is not necessary

- pom.xml
- src/com/googlecode/jmxtrans/model/output/BaseOutputWriter.java
- test/booleanTest.json
- test/com/googlecode/jmxtrans/model/output/BaseOutputWriterTests.java
- test/com/googlecode/jmxtrans/model/output/GraphiteWriterTests.java
I noticed that the property booleanAsNumber (defined in BaseOutputWriter) wasn't working.
This should provide the fix.
I also notice that the boolean property debugEnabled probably doesn't work for the same reasons but I haven't provided a fix for that because I'm not sure if debugEnabled is even still used anywhere..?
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/lookfirst%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/85355%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/267%23issuecomment-92556587%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-04-14T01%3A54%3 …
> Fix boolean as number

- test/com/googlecode/jmxtrans/model/output/GraphiteWriterTests.java
@gehel Please accept my apologies about the broken build. My mistake, those two fixes were developed independently and one of the tests was expecting incorrect behavior fixed in the other branch. This should resolve it.
Two branches, cleanup_allow_dotted and fix_booleanAsNumber were merged
into jmxtrans master. They were developed independently and fixed two
different issues. Unfortunately some of the tests depended on the
incorrect behavior fixed in the other branch and so when both were
merged a test failed. This fixes the issue. The code was correct, it was
the test that needed to change.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/lookfirst%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/85355%3Fv%3D3%22%7D …
> Stopped tests from relying on incorrect behavior

- src/com/googlecode/jmxtrans/model/output/GangliaWriter.java
- src/com/googlecode/jmxtrans/model/results/CPrecisionValueTransformer.java
- test/com/googlecode/jmxtrans/model/results/CPrecisionValueTransformerTests.java
fixes #272
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/275?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/275'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Double underflow error in Ganglia

- src/com/googlecode/jmxtrans/model/naming/StringUtils.java
- test/com/googlecode/jmxtrans/model/naming/StringUtilsTest.java
- test/com/googlecode/jmxtrans/model/output/GraphiteWriterTests.java
Cleaner way to fix the issue I'm seeing with Yammer metrics when they include empty typeNames as was discussed in https://github.com/jmxtrans/jmxtrans/pull/271
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/lookfirst%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/85355%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/277%23issuecomment-94896183%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-04-21T18%3A26%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/85355%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github. …
> Remove empty type names

- pom.xml
Fixes half of the issue raised by #278
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/279%23issuecomment-95806172%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/279%23issuecomment-95806172%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Fixes%20%23280%22%2C%20%22created_at%22%3A%20%222015-04-24T05%3A33%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415765%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/gehel%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'><img …
> to rebaseRenamed jmxtrans daemon from jmxtransd to jmxtrans

- pom.xml
fixes #282
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/284?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/284'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Adding SHA-256 checksum to all artifacts

- pom.xml
- rpm/SPECS/jmxtrans.spec
https://github.com/jmxtrans/jmxtrans/issues/281
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/285%23issuecomment-95857089%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/285%23issuecomment-95857089%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20think%20that%20%60rpm/SPECS/jmxtrans.spec%60%20isn%27t%20used%20at%20all%20anymore.%20We%20should%20probably%20remove%20it%20at%20some%20point%20to%20reduce%20confusion.%20In%20the%20meantime%2C%20aligning%20the%20content%20is%20a%20very%20good%20thing%20%21%22%2C%20%22created_at%22%3A%20%222015-04-24T08%3A51%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.g …
> Don't create jmxtrans user if it exist already

- jmxtrans-output/jmxtrans-output-cloudwatch/pom.xml
- jmxtrans-output/jmxtrans-output-core/pom.xml
- jmxtrans-output/jmxtrans-output-ganglia/pom.xml
- jmxtrans-output/jmxtrans-output-jrobin/pom.xml
- jmxtrans-output/jmxtrans-output-log4j/pom.xml
- jmxtrans-output/jmxtrans-output-velocity/pom.xml
- pom.xml
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/297?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/297'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> COnfigure github site plugin for multi module

- jmxtrans/src/deb/control/control
Rebased #289.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/303?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/303'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Fix deb java dependency

- jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriter.java
- pom.xml
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/308%23issuecomment-110210478%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/308%23issuecomment-110210478%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Replaced%20%23307%20.%22%2C%20%22created_at%22%3A%20%222015-06-09T03%3A21%3A17Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1019609%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/utkarshcmu%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'><img src='http://www.codereviewhub.com/site/github-bar.png' …
> Added author contact.

- pom.xml
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/324?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/324'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Update sortpom plugin and fix maven_color issue

- jmxtrans-output/jmxtrans-output-kafka/pom.xml
- jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriter.java
- jmxtrans-output/jmxtrans-output-kafka/src/test/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriterTests.java
Added a check for topics not to be null.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/325%23issuecomment-135950354%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/325%23issuecomment-136050337%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/325%23issuecomment-135950354%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20am%20seeing%20this%20error%20in%20my%20TravisCI%20build%20while%20running%20the%20KafkaWriterTests%3A%5Cr%5Cn%5Cr%5Cn%5Cr%5Cn%5BERROR%5D%20SLF4J%3A%20Class%20path%20contains%20multiple%20SLF4J%20bindings.%5Cr%5CnSLF4J%3A%20Found%20binding%20in%20%5Bjar%3Afile%3A/home/travis/.m2/repository/ch/qos/logback/logb …
> Fixed Nullpointer exception in KafkaWriter

- pom.xml
See https://github.com/jcgay/maven-color/wiki/Problems for details
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/331?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/331'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Fixed checkstyle dependencies

- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/JmxTransformer.java
- jmxtrans-output/jmxtrans-output-elastic/src/test/java/com/googlecode/jmxtrans/model/output/elastic/ElasticWriterTests.java
- pom.xml
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/332?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/332'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Updated all dependencies and plugins to latest (except a few ...)

- jmxtrans-core/pom.xml
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/ManagedJmxTransformerProcess.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/cli/CliArgumentParser.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/cli/JmxTransConfiguration.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/connections/JMXConnectionParams.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/guice/JmxTransModule.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/lombok.config
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/JmxProcess.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Query.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Result.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Server.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/ValidationException.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/naming/ClassAttributeNamingStrategy.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/naming/typename/TypeNameValue.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/output/BaseOutputWriter.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/monitoring/ManagedGenericKeyedObjectPool.java
- pom.xml
Lombok is now used for some getters and setters in jmxtrans core.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/342?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/342'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Introduced lombok, fixing #187

- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/GraphiteWriter.java
- jmxtrans-utils/pom.xml
- jmxtrans-utils/src/main/java/com/googlecode/jmxtrans/lombok.config
- jmxtrans-utils/src/main/java/com/googlecode/jmxtrans/util/OnlyOnceLogger.java
- jmxtrans-utils/src/test/java/com/googlecode/jmxtrans/util/OnlyOnceLoggerTest.java
This is an alternate implementation for #340
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/343%23issuecomment-150574033%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/343%23issuecomment-150574033%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%2B1%5Cr%5Cn%5Cr%5CnThat%20looks%20great%2C%20thanks%20you%21%22%2C%20%22created_at%22%3A%20%222015-10-23T13%3A33%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3083638%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/bm371613%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a …
> GraphiteWriter: ignore non-numeric

- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/GraphiteWriter.java
- jmxtrans-utils/src/main/java/com/googlecode/jmxtrans/util/OnlyOnceLogger.java
- jmxtrans-utils/src/test/java/com/googlecode/jmxtrans/util/OnlyOnceLoggerTest.java
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/344?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/344'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Minor optimisation: do not do anything if logging is disabled

- jmxtrans-output/jmxtrans-output-cloudwatch/src/main/java/com/googlecode/jmxtrans/model/output/CloudWatchWriter.java
- jmxtrans-output/jmxtrans-output-cloudwatch/src/test/java/com/googlecode/jmxtrans/model/output/CloudWatchWriterTests.java
- jmxtrans-output/jmxtrans-output-cloudwatch/src/test/resources/cloud-watch.json
Added sample JSON from issue report for testing.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/349%23issuecomment-152135825%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/349%23issuecomment-152135825%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Looks%20good%20%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-10-29T10%3A13%3A48Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415765%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/gehel%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'><img …
> Add @JsonIgnore to setCloudWatchClient, fixes #334

- jmxtrans-output/jmxtrans-output-kafka/pom.xml
- pom.xml
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/358?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/358'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> remove dependencies to log4j and replaced it with log4j-over-slf4j

- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StatsDWriter.java
Hello,
Added support to send string values as part of the key for StatsD.
This is necessary as StatsD only support numbers, but you wish to monitor server status, for example Zookeeper.
This PR add two new settings for StatsD:
* ``stringValuesAsKey``: a boolean that enable this feature
* ``stringValueDefaultCount``: when enabled this setting is the count value for the attributes collected.
Fabiano
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/363%23discussion_r45325132%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/363%23issuecomment-158023094%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/363%23issuecomment-158045975%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20 …
> Added support to send string values as key for StatsD.

- jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriter.java
- jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriterFactory.java
- jmxtrans-output/jmxtrans-output-influxdb/src/test/java/com/googlecode/jmxtrans/model/output/InfluxDbWriterTests.java
fixes #368
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/369?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/369'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Adding flag to configure InfluxDbWriter to create (or not) the database

- jmxtrans-core/src/test/resources/log4j.xml
- jmxtrans-output/jmxtrans-output-cloudwatch/src/test/resources/log4j.xml
- jmxtrans-output/jmxtrans-output-core/src/test/resources/log4j.xml
- jmxtrans-output/jmxtrans-output-elastic/src/test/resources/log4j.xml
- jmxtrans-output/jmxtrans-output-ganglia/src/test/resources/log4j.xml
- jmxtrans-output/jmxtrans-output-influxdb/src/test/resources/log4j.xml
- jmxtrans-output/jmxtrans-output-kafka/src/test/resources/log4j.xml
- jmxtrans-utils/src/test/resources/log4j.xml
This should ensure better ouput during test phase
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/379?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/379'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Adding log4j.xml configuration to tests

- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/JmxTransformer.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/jmx/ProcessQueryThread.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Server.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/GraphiteWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/LibratoWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/SensuWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StatsDWriter.java
To prepare the way for more drastic changes, let's try to remove / change a few functionalities
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/381?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/381'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Add a few deprecation warnings

- jmxtrans-core/pom.xml
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/jmx/JmxUtils.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/jmx/ProcessQueryThread.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Server.java
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/385?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/385'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> OutputWriters can now be configured on server

- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Query.java
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/386?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/386'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Make sure we can create a query with no OuptutWriter

- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/monitoring/ManagedThreadPoolExecutor.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/monitoring/ThreadPoolExecutorMXBean.java
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/388%23issuecomment-167957281%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/388%23issuecomment-167957281%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Additional%20fix%20for%20%23384%22%2C%20%22created_at%22%3A%20%222015-12-30T08%3A31%3A00Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415765%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/gehel%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'><img src='http://www.codereviewhub.com/site/github-bar.png' …
> Fixed broken MXBean implementation for monitoring thread pools

- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Result.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/Slf4JOutputWriter.java
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/397?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/397'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Removed unnecessary null check

- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/ConfigurationParser.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/ServerListBuilder.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Query.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Server.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/ServerFixtures.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/naming/typename/PrependingTypeNameValuesStringBuilder.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/naming/typename/TypeNameValuesStringBuilder.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/naming/typename/UseAllTypeNameValuesStringBuilder.java
- jmxtrans-core/src/test/java/com/googlecode/jmxtrans/ServerListBuilderTest.java
- jmxtrans-output/jmxtrans-output-core/pom.xml
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/GraphiteWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/GraphiteWriterFactory.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/LibratoWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/LibratoWriterFactory.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/SensuWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/SensuWriterFactory.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/Slf4JOutputWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StackdriverWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StatsDWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StatsDWriterFactory.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/lombok.config
> Deduplicate output writers

- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/util/JsonUtils.java
- jmxtrans-core/src/test/java/com/googlecode/jmxtrans/util/JsonUtilsTest.java
- jmxtrans-core/src/test/resources/exampleWithVariables.json
- jmxtrans-test-utils/src/main/java/com/googlecode/jmxtrans/test/ResetableSystemProperty.java
Add some test to JSONUtilsTest
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/406%23discussion_r50107754%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/406%23discussion_r50107805%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/406%23discussion_r50107845%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/406%23issuecomment-172843435%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/406%23issuecomment-172843435%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Could%20you%20squash%20all%20before%20I%20merge%20%3F%22%2C%20%22created_at%22%3A%20%222016-01-19T12%3A48%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20 …
> improve tests for JSONUtils

- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/LibratoWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/LibratoWriter2.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/OpenTSDBGenericWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/SensuWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StackdriverWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StatsDWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StatsDWriter2.java
- jmxtrans-output/jmxtrans-output-jrobin/src/main/java/com/googlecode/jmxtrans/model/output/RRDToolWriter.java
- jmxtrans-output/jmxtrans-output-jrobin/src/main/java/com/googlecode/jmxtrans/model/output/RRDWriter.java
- jmxtrans-output/jmxtrans-output-log4j/src/main/java/com/googlecode/jmxtrans/model/output/KeyOutWriter.java
- jmxtrans-output/jmxtrans-output-log4j/src/main/java/com/googlecode/jmxtrans/model/output/Log4JWriter.java
- jmxtrans-output/jmxtrans-output-log4j/src/main/java/com/googlecode/jmxtrans/model/output/NagiosWriter.java
- jmxtrans-utils/pom.xml
- jmxtrans-utils/src/main/java/com/googlecode/jmxtrans/util/NumberUtils.java
- jmxtrans-utils/src/test/java/com/googlecode/jmxtrans/util/NumberUtilsTest.java
Let's use Apache commons almost directly and remove our custom implementation.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/407?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/407'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Cleanup NumberUtils

- jmxtrans-core/src/test/java/com/googlecode/jmxtrans/util/PropertyResolverTest.java
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/412?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/412'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> replace system.setProperty by resetableSystemProperty

- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/ServerListBuilder.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/ResultAttribute.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/naming/typename/TypeNameValue.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/LibratoWriter2.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/SensuWriter2.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/Slf4JOutputWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/support/HttpOutputWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/support/pool/ChannelWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/support/pool/DatagramChannelAllocator.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/support/pool/SocketAllocator.java
- jmxtrans-output/jmxtrans-output-kafka/pom.xml
- jmxtrans-test-utils/src/main/java/com/googlecode/jmxtrans/test/Counter.java
- jmxtrans/pom.xml
- pom.xml
* fixed some new CHeckstyle warnings
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/415?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/415'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> update dependencies to latest working version

- jmxtrans-output/jmxtrans-output-cloudwatch/pom.xml
- jmxtrans-output/jmxtrans-output-cloudwatch/src/main/java/com/googlecode/jmxtrans/model/output/CloudWatchWriter.java
- jmxtrans-output/jmxtrans-output-cloudwatch/src/main/java/com/googlecode/jmxtrans/model/output/MapEntryToDimension.java
- jmxtrans-output/jmxtrans-output-cloudwatch/src/test/java/com/googlecode/jmxtrans/model/output/CloudWatchWriterIT.java
- jmxtrans-output/jmxtrans-output-cloudwatch/src/test/java/com/googlecode/jmxtrans/model/output/CloudWatchWriterTests.java
- jmxtrans-output/jmxtrans-output-cloudwatch/src/test/java/com/googlecode/jmxtrans/model/output/MapEntryToDimensionTest.java
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/416?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/416'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Make CloudWatchWriter a bit easier to test and to isolate long running tests

- jmxtrans-output/jmxtrans-output-core/src/test/java/com/googlecode/jmxtrans/model/output/GraphiteWriterFactoryIT.java
- jmxtrans-output/jmxtrans-output-core/src/test/resources/graphite-writer-factory-example.json
@hgomez: here is an integration test showing the proper format for configuring the new GraphiteWriterFactory.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/430%23issuecomment-200437281%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/430%23issuecomment-200437281%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22LGTM%22%2C%20%22created_at%22%3A%20%222016-03-23T16%3A50%3A58Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/274370%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/hgomez%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a …
> adding integration test for GraphitWriterFactory

- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/guice/JmxTransModule.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Server.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/output/StdOutWriter.java
- jmxtrans-examples/src/main/java/com/googlecode/jmxtrans/example/ActiveMQ.java
- jmxtrans-examples/src/main/java/com/googlecode/jmxtrans/example/ActiveMQ2.java
- jmxtrans-examples/src/main/java/com/googlecode/jmxtrans/example/Ehcache.java
- jmxtrans-examples/src/main/java/com/googlecode/jmxtrans/example/Ganglia.java
- jmxtrans-examples/src/main/java/com/googlecode/jmxtrans/example/Graphite.java
- jmxtrans-examples/src/main/java/com/googlecode/jmxtrans/example/HeapMemory.java
- jmxtrans-examples/src/main/java/com/googlecode/jmxtrans/example/Hibernate.java
- jmxtrans-examples/src/main/java/com/googlecode/jmxtrans/example/InterestingInfo.java
- jmxtrans-examples/src/main/java/com/googlecode/jmxtrans/example/Local.java
- jmxtrans-examples/src/main/java/com/googlecode/jmxtrans/example/MemoryPool.java
- jmxtrans-examples/src/main/java/com/googlecode/jmxtrans/example/Tester.java
- jmxtrans-examples/src/main/java/com/googlecode/jmxtrans/example/TreeWalker3.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/LibratoWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/SensuWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/SensuWriter2.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/support/HttpOutputWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/support/pool/NeverFlush.java
- jmxtrans-output/jmxtrans-output-jrobin/src/main/java/com/googlecode/jmxtrans/model/output/RRDToolWriter.java
- jmxtrans-output/jmxtrans-output-kafka/pom.xml
- jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriter.java
- jmxtrans-test-utils/src/main/java/com/googlecode/jmxtrans/test/DummyApp.java
- jmxtrans-test-utils/src/main/java/com/googlecode/jmxtrans/test/OutputCapture.java
- jmxtrans-test-utils/src/main/java/com/googlecode/jmxtrans/test/TCPEchoServer.java
- pom.xml
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/439?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/439'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Correct sonarqube issues

- .travis.yml
- README.md
- travis-script.sh
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/450?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/450'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Adding SonarQube integration to travis build

- jmxtrans-output/jmxtrans-output-ganglia/src/main/java/com/googlecode/jmxtrans/model/output/GangliaWriter.java
Fixes #466
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/467?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/467'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Close GMetric properly when sending metrics to Ganglia.

- README.md
- jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriter.java
- jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriterFactory.java
- jmxtrans-output/jmxtrans-output-influxdb/src/test/java/com/googlecode/jmxtrans/model/output/InfluxDbWriterTests.java
- jmxtrans-output/jmxtrans-output-influxdb/src/test/resources/influxDB.json
- travis-script.sh
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/477?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/477'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> next release

- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/naming/JexlNamingStrategy.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/SensuWriter.java
- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StackdriverWriter.java
- jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriter.java
- jmxtrans-output/jmxtrans-output-log4j/src/main/java/com/googlecode/jmxtrans/model/output/NagiosWriter.java
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/474?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/474'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> fixed convention issues

- jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/OpenTSDBGenericWriter.java
Fixes #487.
<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/493?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/493'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Make sure typenames are non null in OpenTSDBWriter

- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/cli/CliArgumentParser.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/cli/FileConfiguration.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/cli/JCommanderArgumentParser.java
- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/cli/JmxTransConfiguration.java
- jmxtrans-core/src/main/resources/jmxtrans.properties
- jmxtrans-core/src/test/java/com/googlecode/jmxtrans/cli/CliArgumentParserBase.java
- jmxtrans-core/src/test/java/com/googlecode/jmxtrans/cli/JCommanderArgumentParserTest.java
- jmxtrans-docker-test/pom.xml
- jmxtrans-packaging/jmxtrans-systemd/pom.xml
- jmxtrans-packaging/jmxtrans-systemd/src/deb/control/control
- jmxtrans-packaging/jmxtrans-systemd/src/deb/control/preinst
- jmxtrans-packaging/jmxtrans-systemd/src/etc/jmxtrans
- jmxtrans-packaging/jmxtrans-systemd/src/etc/jmxtrans.default
- jmxtrans-packaging/jmxtrans-systemd/src/etc/jmxtrans.service
- jmxtrans-packaging/jmxtrans-systemd/src/etc/log4j.xml
- jmxtrans-packaging/pom.xml
- pom.xml
I'm trying to put some order into .deb and .rpm packaging. This will
require a few iterations, probably some changes to jmxtrans itself
and reviews from people who actually understand all that packaging
stuff...
Definitely work in progress!
> new packaging

- jmxtrans/tools/yaml2jmxtrans.py
yaml2jmxtrans doesn't write settings element to json config now
> fix issue #484

- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/results/CPrecisionValueTransformer.java
- jmxtrans-core/src/test/java/com/googlecode/jmxtrans/model/results/CPrecisionValueTransformerTests.java
> Handle NaN values in CPrecisionValueTransformer

- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/JmxTransformer.java
Triggers name are  generated with currentTimeMillis() and in some case two triggers can have same generated name.
That cause the following error on the service loading :
> ERROR (com.googlecode.jmxtrans.JmxTransformer:190) - Error scheduling job for server: 
> Caused by: org.quartz.ObjectAlreadyExistsException: Unable to store Trigger with name: 'test.nespresso.com:9200-1490623007618' and group: 'DEFAULT', because one already exists with this identification.
I have replace  currentTimeMillis() by nanoTime() to fix this issue.
> Fix: ObjectAlreadyExistsException because one already exists

- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/JmxTransformer.java
> run period seconds was ignored if set at the server level

- README.md
Fixed the Markdown link for the French link
> Minor: Fix Markdown for link in README.md

- jmxtrans-output/jmxtrans-output-kafka/pom.xml
- jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/DefaultResultSerializer.java
- jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/DetailedResultSerializer.java
- jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriter.java
- jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriter2.java
- jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriterFactory.java
- jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/ResultSerializer.java
- jmxtrans-output/jmxtrans-output-kafka/src/main/java/com/googlecode/jmxtrans/model/output/kafka/lombok.config
- jmxtrans-output/jmxtrans-output-kafka/src/test/java/com/googlecode/jmxtrans/model/output/kafka/DefaultResultSerializerTest.java
- jmxtrans-output/jmxtrans-output-kafka/src/test/java/com/googlecode/jmxtrans/model/output/kafka/DetailedResultSerializerTest.java
- jmxtrans-output/jmxtrans-output-kafka/src/test/java/com/googlecode/jmxtrans/model/output/kafka/EmbeddedKafka.java
- jmxtrans-output/jmxtrans-output-kafka/src/test/java/com/googlecode/jmxtrans/model/output/kafka/EmbeddedZookeeper.java
- jmxtrans-output/jmxtrans-output-kafka/src/test/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriter2Test.java
- jmxtrans-output/jmxtrans-output-kafka/src/test/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriterFactoryTest.java
- jmxtrans-output/jmxtrans-output-kafka/src/test/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriterIT.java
- jmxtrans-output/jmxtrans-output-kafka/src/test/java/com/googlecode/jmxtrans/model/output/kafka/KafkaWriterTests.java
- jmxtrans-output/jmxtrans-output-kafka/src/test/resources/jmxtrans-kafka.json
- jmxtrans-output/jmxtrans-output-kafka/src/test/resources/kafka-writer-default.json
- jmxtrans-output/jmxtrans-output-kafka/src/test/resources/kafka-writer-default2.json
- jmxtrans-output/jmxtrans-output-kafka/src/test/resources/kafka-writer-detailed.json
- jmxtrans-output/jmxtrans-output-kafka/src/test/resources/kafka-writer-detailed2.json
- jmxtrans-output/jmxtrans-output-kafka/src/test/resources/kafka.properties
- jmxtrans-output/jmxtrans-output-kafka/src/test/resources/zookeeper.properties
- pom.xml
I tried to split Writer from WriterFactory: is this what you're expecting?
Can you give me some feedback about the design?
> New Kafka Writer

- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/JmxResultProcessor.java
I tried to make the JmxResultProcessor cleaner by:
* Creating and internal Result value walker/accumulator instead of passing the List.Builder to each method
* Replacing TabularDataSupport/CompositeDataSupport by their interface counterpart TabularData/CompositeData
* Extracted each if block from the original getResult method in its method. Split the getResult method in small pieces.
* Factorised the Result r = getNewResultObject(...) + accumulator.add(r) pattern in a addNew method
It behaves like the original version
> Refactor JmxResultProcessor

- pom.xml
> Update version of AWS libraries

- jmxtrans/tools/yaml2jmxtrans.py
Nothing fancy, just some cleanup while reading through the script. I am planning to add support for influxdb next.
> Tabs vs spaces cleanup

- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Server.java
- jmxtrans-core/src/test/java/com/googlecode/jmxtrans/model/ServerTests.java
> Fix NPE when connecting with PID

- jmxtrans-core/pom.xml
- jmxtrans-docker-test/pom.xml
- jmxtrans-examples/pom.xml
- jmxtrans-output/jmxtrans-output-cloudwatch/pom.xml
- jmxtrans-output/jmxtrans-output-core/pom.xml
- jmxtrans-output/jmxtrans-output-elastic/pom.xml
- jmxtrans-output/jmxtrans-output-influxdb/pom.xml
- jmxtrans-output/jmxtrans-output-kafka/pom.xml
- jmxtrans-test-utils/pom.xml
- jmxtrans-utils/pom.xml
- pom.xml
spotbugs is the successor of findbugs
> replace findbugs with spotbugs

- jmxtrans/docker/Dockerfile
The goal is to reduce the size of the image.
> Going for openjdk-apline + automate last jmxtrans version

- jmxtrans-core/src/main/java/com/googlecode/jmxtrans/JmxTransformer.java
> Fix: ignore dot files in the monitored directory

- jmxtrans-output/jmxtrans-output-kafka/pom.xml
- pom.xml
Also upgrade Kafka which is related
https://github.com/jmxtrans/jmxtrans/network/alert/pom.xml/org.apache.zookeeper:zookeeper/open
> security: Upgrade Zookeeper dependency

- jmxtrans-packaging/jmxtrans-systemd/src/etc/jmxtrans.service
- jmxtrans/jmxtrans-init.sh
- jmxtrans/jmxtrans.service
- jmxtrans/jmxtrans.sh
- jmxtrans/src/assembly/dist.xml
- jmxtrans/src/deb/init.d/jmxtrans
Split jmxtrans.sh in jmxtrans.sh + jmxtrans-init.sh
* jmxtrans.sh is called from both initd and systemd
* jmxtrans-init.sh is used for legacy initd systems
Add jmxtrans service unit example
> systemd support in tarball
